### ISSUE TITLE
Tarea 1: duda métricas de evaluación de modelos

### ISSUE THREAD

**Issue by VicenteGM123** [PUC-RecSys-Class/RecSysPUC-2022#2]
Hola! ¿Para todos los modelos hay que evaluar el desempeño mediante ndcg@10, ndcg@20, ndcg@30, MAP@10, MAP@20 y MAP@30? O sólo para la actividad 2? Lo pregunto porque en las demás actividades solo dice que usemos MAP@10 y ndcg@10.

Saludos

**Comment by nsumonte** [comment]
Hola Vicente!
En todos los modelos debes evaluar el desempeño mediante ndcg@10, ndcg@20, ndcg@30, MAP@10, MAP@20 y reportar estas métricas en tu informe. Sin embargo, el **análisis de sensibilidad** (en las actividades que se pide) debe realizarse sobre las métricas ndcg@10 y MAP@10.
Espero haber respondido tu duda!

**Comment by VicenteGM123** [comment]
Sí, respondiste mi duda. Muchas gracias!
